# Generated by Django 5.1.4 on 2025-01-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('AD', 'Admin'), ('CU', 'Customer'), ('TS', 'Tour_Staff'), ('TG', 'Tour_Guider')], default='CU', max_length=2),
        ),
    ]
