# Generated by Django 5.1.4 on 2025-01-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_initial'),
        ('users', '0004_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourguider',
            name='assigned_packages',
            field=models.ManyToManyField(blank=True, related_name='tour_guiders', to='packages.packages'),
        ),
    ]
