# Generated by Django 5.1.2 on 2024-12-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('AD', 'Admin'), ('CU', 'Customer'), ('TS', 'Tour_Staff')], default='CU', max_length=2),
        ),
    ]
