# Generated by Django 5.1.2 on 2024-12-25 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_packages_status_subpackages'),
        ('users', '0006_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('AD', 'Admin'), ('CU', 'Customer'), ('TS', 'Tour_Staff'), ('Td', 'Tour_Guider')], default='CU', max_length=2),
        ),
        migrations.CreateModel(
            name='TourGuider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('assigned_packages', models.ManyToManyField(related_name='tour_guiders', to='packages.packages')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
