# Generated by Django 5.1.2 on 2024-12-25 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofile_role_tourguider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourguider',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tour_guider', to='users.userprofile'),
        ),
    ]
