# Generated by Django 5.1.2 on 2024-12-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_tourguider_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('AD', 'Admin'), ('CU', 'Customer'), ('TS', 'Tour_Staff'), ('Tg', 'Tour_Guider')], default='CU', max_length=2),
        ),
    ]
