# Generated by Django 5.1.4 on 2025-01-04 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='packagereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packages',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packagereview',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_review', to='packages.packages'),
        ),
        migrations.AddField(
            model_name='packageimages',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='packages.packages'),
        ),
        migrations.AddField(
            model_name='subpackages',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subpackages', to='packages.packages'),
        ),
        migrations.AddIndex(
            model_name='packages',
            index=models.Index(fields=['-publish'], name='packages_pa_publish_6c262c_idx'),
        ),
    ]
