# Generated by Django 5.1.2 on 2024-12-24 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='status',
            field=models.CharField(choices=[('PB', 'Publish'), ('DR', 'Draft')], default='DR', max_length=2),
        ),
        migrations.CreateModel(
            name='SubPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subpackage_name', models.CharField(max_length=100)),
                ('subpackage_description', models.TextField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subpackages', to='packages.packages')),
            ],
        ),
    ]
