# Generated by Django 5.1.4 on 2025-01-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_alter_packageimages_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subpackages',
            name='subpackage_image',
            field=models.ImageField(blank=True, null=True, upload_to='subpackage_image/'),
        ),
    ]
