# Generated by Django 5.1.2 on 2024-12-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_packagereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagereview',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
    ]
