# Generated by Django 5.1.2 on 2024-12-25 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_alter_packagereview_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagereview',
            old_name='rating',
            new_name='rate',
        ),
    ]
