# Generated by Django 5.1.2 on 2024-12-25 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_rename_rating_packagereview_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagereview',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_review', to='packages.packages'),
        ),
    ]
