# Generated by Django 5.1.4 on 2024-12-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_alter_packagereview_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='package_name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
