# Generated by Django 5.1.4 on 2025-01-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bankist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(editable=False, max_length=14, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pin', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[('Withdrawal', 'WITHDRAWAl'), ('Deposit', 'Deposit'), ('Transfer', 'Transfer')], max_length=10)),
            ],
        ),
    ]
