# Generated by Django 5.1.2 on 2024-12-27 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0010_alter_userprofile_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bankist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(editable=False, max_length=14, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pin', models.CharField(max_length=128)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='users.userprofile')),
            ],
        ),
    ]
