# Generated by Django 5.1.4 on 2025-01-04 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bankist', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankist',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_history', to='Bankist.bankist'),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='related_transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paired_transaction', to='Bankist.transactionhistory'),
        ),
    ]
