# Generated by Django 5.1.4 on 2024-12-27 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bankist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[('Withdrawal', 'WITHDRAWAl'), ('Deposit', 'Deposit'), ('Transfer', 'Transfer')], max_length=10)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_history', to='Bankist.bankist')),
                ('related_transaction', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paired_transaction', to='Bankist.transactionhistory')),
            ],
        ),
    ]
