# Generated by Django 5.1.2 on 2025-01-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bankist', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankist',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
