# Generated by Django 5.1.4 on 2025-01-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('number_of_people', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'PENDING'), ('Confirmed', 'CONFIRMED'), ('Canceled', 'CANCELED')], default='Pending', max_length=20)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
    ]
