# Generated by Django 5.1.4 on 2024-12-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_package_alter_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Confirmed', 'CONFIRMED'), ('Canceled', 'CANCELED')], default='Pending', max_length=20),
        ),
    ]
